apiVersion: batch/v1
kind: Job
metadata:
  name: almoghershko-train-nn-2
spec:
  backoffLimit: 0
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-2080-Ti
                - NVIDIA-GeForce-RTX-3090
                - Tesla-V100-SXM2-32GB
                - NVIDIA-A10
                - NVIDIA-A100-SXM4-80GB
                - NVIDIA-A100-80GB-PCIe
                - NVIDIA-A100-PCIE-40GB-MIG-2g.10gb
                - NVIDIA-A100-80GB-PCIe-MIG-1g.10gb
      containers:
      - name: container
        image: almogh/tf-almog
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu:  "4"
          limits:
            cpu: "8"
            memory: "32Gi"
            nvidia.com/gpu:  "4"
        command: ["/bin/bash", "-c"]
        args:
          - cd root; 
            git clone https://github.com/almoghershko/thesis2.git;
            pip install -r thesis/requirements.txt;
            python thesis2/scripts/train_NN.py $MODEL_NAME &> stdout.txt;
            aws --endpoint https://s3-west.nrp-nautilus.io s3 cp ./stdout.txt s3://tau-astro/almogh/thesis2/models/$MODEL_NAME/train/;
            tar -zcvf logs.tar.gz logs
            aws --endpoint https://s3-west.nrp-nautilus.io s3 cp ./logs.tar.gz s3://tau-astro/almogh/thesis2/models/$MODEL_NAME/train/;
        env:
          - name: "MODEL_NAME"
            value: "NN2"
      restartPolicy: Never
